# TCL File Generated by Component Editor 13.1
# Tue Aug 02 15:46:25 EDT 2016
# DO NOT MODIFY


# 
# EchoStateNetwork_7Units_Expanded "ESN7e" v1.0
# KU_Liugroup 2016.08.02.15:46:25
# A spatially expanded echo state network implementation that uses RAM to store inputs and teacher output data
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module EchoStateNetwork_7Units_Expanded
# 
set_module_property DESCRIPTION "A spatially expanded echo state network implementation that uses RAM to store inputs and teacher output data"
set_module_property NAME EchoStateNetwork_7Units_Expanded
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DSP
set_module_property AUTHOR KU_Liugroup
set_module_property DISPLAY_NAME ESN7e
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL esn7e_st_src
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file esn7e_st_src.v VERILOG PATH esn7e_st_src.v
add_fileset_file esn_top.v VERILOG PATH ../esn7_e/esn_top.v
add_fileset_file rdout_rst_sreg.v VERILOG PATH ../esn7_e/rdout_rst_sreg.v
add_fileset_file addr_ctr.v VERILOG PATH ../esn7_e/res/addr_ctr.v
add_fileset_file res_top.v VERILOG PATH ../esn7_e/res/res_top.v
add_fileset_file slow_Ctr.v VERILOG PATH ../esn7_e/res/slow_Ctr.v
add_fileset_file rdout_top.v VERILOG PATH ../esn7_e/rdout/rdout_top.v
add_fileset_file pe_16x1_hybrid_trunc.v VERILOG PATH ../esn7_e/pe/pe_16x1_hybrid_trunc.v
add_fileset_file pe_8x2_hybrid.v VERILOG PATH ../esn7_e/pe/pe_8x2_hybrid.v
add_fileset_file pe_8x4_16bit.v VERILOG PATH ../esn7_e/pe/pe_8x4_16bit.v
add_fileset_file tf_inv.v VERILOG PATH ../esn7_e/pe/tf/tf_inv.v
add_fileset_file tf_inv_mem.v VERILOG PATH ../esn7_e/pe/tf/tf_inv_mem.v
add_fileset_file tf_tanh.v VERILOG PATH ../esn7_e/pe/tf/tf_tanh.v
add_fileset_file tf_tanh_mem.v VERILOG PATH ../esn7_e/pe/tf/tf_tanh_mem.v
add_fileset_file inv_interp_LUT.mif MIF PATH ../esn7_e/pe/tf/inv_interp_LUT.mif
add_fileset_file tanh_interp_LUT.mif MIF PATH ../esn7_e/pe/tf/tanh_interp_LUT.mif
add_fileset_file mul16x16to32.v VERILOG PATH ../esn7_e/pe/mul/mul16x16to32.v
add_fileset_file mul16x32to48.v VERILOG PATH ../esn7_e/pe/mul/mul16x32to48.v
add_fileset_file mul18x18to36.v VERILOG PATH ../esn7_e/pe/mul/mul18x18to36.v
add_fileset_file mul32x32to32.v VERILOG PATH ../esn7_e/pe/mul/mul32x32to32.v
add_fileset_file mul32x32to48.v VERILOG PATH ../esn7_e/pe/mul/mul32x32to48.v
add_fileset_file add36x36signed_sub.v VERILOG PATH ../esn7_e/pe/add/add36x36signed_sub.v
add_fileset_file add_16x16signed.v VERILOG PATH ../esn7_e/pe/add/add_16x16signed.v
add_fileset_file add_32x32signed.v VERILOG PATH ../esn7_e/pe/add/add_32x32signed.v
add_fileset_file add_48x48signed.v VERILOG PATH ../esn7_e/pe/add/add_48x48signed.v
add_fileset_file padd_8x36signed_to_1x38signed.v VERILOG PATH ../esn7_e/pe/add/padd_8x36signed_to_1x38signed.v
add_fileset_file padd_8x38signed_to_1x41signed.v VERILOG PATH ../esn7_e/pe/add/padd_8x38signed_to_1x41signed.v
add_fileset_file padd_8x51signed_to1x54signed.v VERILOG PATH ../esn7_e/pe/add/padd_8x51signed_to1x54signed.v
add_fileset_file input_data.mif MIF PATH ../esn7_e/mem/input_data.mif
add_fileset_file input_ROM.v VERILOG PATH ../esn7_e/mem/input_ROM.v
add_fileset_file output_data.mif MIF PATH ../esn7_e/mem/output_data.mif
add_fileset_file true_output_ROM.v VERILOG PATH ../esn7_e/mem/true_output_ROM.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 1000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 32
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source data_valid valid Output 1
add_interface_port avalon_streaming_source data_out data Output 32

